export interface Community {
  slug: string
  name: string
  location: string
  city: string
  description: string
  longDescription: string
  amenities: string[]
  floorplans: string[]
  homesForSale: number
  featured: boolean
  yearBuilt?: string
  homeCount?: number
  priceRange?: string
  size?: string
  category?: 'mega' | 'large' | 'mid-size' | 'premium' | 'value' | 'continuing-care'
}

export const lasVegasCommunities: Community[] = [
  // MEGA COMMUNITIES (5,000+ homes)
  {
    slug: 'sun-city-summerlin',
    name: 'Sun City Summerlin',
    location: 'Summerlin, Las Vegas, NV',
    city: 'Las Vegas',
    description: 'Premier 55+ gated community with 3 golf courses, 4 clubhouses, and resort-style amenities',
    longDescription: 'Sun City Summerlin is Las Vegas\'s largest and most established 55+ community, featuring 7,700+ homes across 2,400+ acres in the prestigious Summerlin master plan. This mega-community offers residents an unparalleled lifestyle with three championship golf courses, four recreation centers, over 80 clubs and organizations, multiple resort-style pools, state-of-the-art fitness centers, theaters, and a vibrant social scene.',
    amenities: [
      'Three championship golf courses',
      'Four recreation centers',
      '80+ clubs and organizations',
      'Multiple resort-style pools',
      'State-of-the-art fitness centers',
      'Theaters and entertainment venues',
      'Tennis and pickleball courts',
      'Arts and crafts studios',
      'Libraries and computer labs',
      'Restaurants and cafes',
    ],
    floorplans: ['Single-story detached homes', 'Attached villas', 'Homes ranging from 1,200 to 3,500 sq ft', '17 distinct floor plans'],
    homesForSale: 24,
    featured: true,
    yearBuilt: '1997',
    homeCount: 7700,
    priceRange: '$350,000 - $1,000,000+',
    size: '2,400+ acres',
    category: 'mega',
  },
  {
    slug: 'sun-city-anthem',
    name: 'Sun City Anthem',
    location: 'Henderson, NV (Anthem Master Plan)',
    city: 'Henderson',
    description: 'Premier Henderson 55+ community with 77,000 sq ft Anthem Center and 3 clubhouses',
    longDescription: 'Sun City Anthem in Henderson is one of Las Vegas\'s largest 55+ communities with over 7,000 homes nestled within the Anthem master plan. The community features the spectacular 77,000 square foot Anthem Center with theater, three additional clubhouses, championship golf, over 80 clubs, state-of-the-art fitness facilities, indoor and outdoor pools, and a vibrant calendar of social activities.',
    amenities: [
      '77,000 sq ft Anthem Center with theater',
      'Three recreation centers',
      'Championship golf courses',
      '80+ clubs and organizations',
      'State-of-the-art fitness centers',
      'Indoor and outdoor pools',
      'Tennis and pickleball courts',
      'Woodworking and arts studios',
      'Restaurants and gathering spaces',
    ],
    floorplans: ['Single-story homes', 'Attached and detached options', 'Homes from 1,100 to 3,000+ sq ft'],
    homesForSale: 18,
    featured: true,
    yearBuilt: '1999',
    homeCount: 7000,
    priceRange: '$350,000 - $800,000',
    category: 'mega',
  },
  // LARGE COMMUNITIES (1,500-3,000+ homes)
  {
    slug: 'sun-city-macdonald-ranch',
    name: 'Sun City MacDonald Ranch',
    location: 'Henderson, NV',
    city: 'Henderson',
    description: 'Championship golf community with 36,000 sq ft clubhouse in foothills near Black Mountain',
    longDescription: 'Sun City MacDonald Ranch offers 2,500+ homes in the scenic foothills of Henderson near Black Mountain. This Del Webb community features a championship golf course, 36,000 square foot clubhouse, tennis and pickleball courts, bocce ball, spa facilities, state-of-the-art fitness center, and stunning mountain views throughout the community.',
    amenities: [
      'Championship 18-hole golf course',
      '36,000 sq ft recreation center',
      'Tennis and pickleball courts',
      'Bocce ball courts',
      'Spa and wellness facilities',
      'State-of-the-art fitness center',
      'Swimming pools',
      'Arts and crafts studios',
      'Scenic mountain views',
    ],
    floorplans: ['Single-story homes', 'Various floor plans', 'Homes from 1,300 to 3,200 sq ft'],
    homesForSale: 10,
    featured: false,
    yearBuilt: '2002',
    homeCount: 2500,
    priceRange: '$400,000 - $900,000',
    category: 'large',
  },
  {
    slug: 'sun-city-aliante',
    name: 'Sun City Aliante',
    location: 'North Las Vegas, NV',
    city: 'North Las Vegas',
    description: 'Award-winning community with 18-hole Aliante Golf Club',
    longDescription: 'Sun City Aliante in North Las Vegas features 2,000+ homes surrounding the prestigious 18-hole Aliante Golf Club. This award-winning community offers championship golf course frontage, multiple clubs, recreation facilities, fitness centers, pools, and a strong sense of community with nearby casino/theater complex.',
    amenities: [
      '18-hole Aliante Golf Club',
      'Golf course frontage options',
      'Recreation facilities',
      'Fitness centers',
      'Swimming pools',
      'Social clubs',
      'Walking trails',
      'Nearby casino/theater complex',
    ],
    floorplans: ['Single-story homes', 'Golf course frontage available', 'Homes from 1,200 to 2,800 sq ft'],
    homesForSale: 8,
    featured: false,
    yearBuilt: '2004',
    homeCount: 2000,
    priceRange: '$300,000 - $700,000',
    category: 'large',
  },
  {
    slug: 'solera-anthem',
    name: 'Solera at Anthem',
    location: 'Henderson, NV (Anthem Master Plan)',
    city: 'Henderson',
    description: 'Affordable 55+ community with modern amenities in Anthem',
    longDescription: 'Solera at Anthem offers 1,800+ homes as a more affordable option while maintaining quality amenities. This community features a modern clubhouse, fitness center, pools, sports courts, walking trails, parks, and access to Anthem master plan amenities.',
    amenities: [
      'Modern clubhouse',
      'Fitness center',
      'Swimming pools',
      'Sports courts',
      'Walking trails',
      'Parks and green spaces',
      'Social activities',
      'Access to Anthem amenities',
    ],
    floorplans: ['Single-story homes', 'Modern designs', 'Homes from 1,300 to 2,500 sq ft'],
    homesForSale: 5,
    featured: false,
    yearBuilt: '2015',
    homeCount: 1800,
    priceRange: '$300,000 - $600,000',
    category: 'large',
  },
  {
    slug: 'siena',
    name: 'Siena',
    location: 'Summerlin, Las Vegas, NV',
    city: 'Las Vegas',
    description: 'Upscale golf community with championship course and lake views in Summerlin',
    longDescription: 'Siena is an upscale 55+ community featuring 800+ homes on 667 acres in prestigious Summerlin. This master-planned community offers an 18-hole championship golf course, Tuscan-inspired architecture, luxury clubhouse, lake views, mountain views, gated security, multiple pools, fitness centers, tennis and bocce courts, and beautifully designed homes.',
    amenities: [
      '18-hole championship golf course',
      'Lake views',
      'Mountain views',
      'Gated community',
      'Luxury clubhouse',
      'Multiple swimming pools',
      'Fitness centers',
      'Tennis and bocce courts',
      'Walking trails',
    ],
    floorplans: ['Luxury single-story homes', 'Homes from 1,400 to 4,000+ sq ft', 'Multiple architectural styles'],
    homesForSale: 12,
    featured: true,
    yearBuilt: '2000',
    homeCount: 800,
    priceRange: '$400,000 - $1,200,000+',
    size: '667 acres',
    category: 'premium',
  },
  // MID-SIZE COMMUNITIES (400-800 homes)
  {
    slug: 'del-webb-lake-las-vegas',
    name: 'Del Webb at Lake Las Vegas',
    location: 'Henderson, NV (Lake Las Vegas)',
    city: 'Henderson',
    description: 'Newest luxury waterfront community with Mediterranean-style homes',
    longDescription: 'Del Webb at Lake Las Vegas is the newest luxury 55+ community, featuring 461 planned Mediterranean-style homes with waterfront views on Lake Las Vegas. This resort-style community offers a 10,000 square foot clubhouse, fitness center, pools, tennis, bocce, pickleball, access to championship golf courses, boating on Lake Las Vegas, and exceptional active adult lifestyle.',
    amenities: [
      '10,000 sq ft clubhouse',
      'Waterfront views on Lake Las Vegas',
      'Fitness center',
      'Resort-style pools',
      'Tennis, bocce, and pickleball courts',
      'Golf courses nearby',
      'Boating and water recreation',
      'Mediterranean architecture',
    ],
    floorplans: ['Mediterranean-style homes', 'Waterfront options', 'Homes from 1,500 to 3,000+ sq ft'],
    homesForSale: 3,
    featured: true,
    yearBuilt: '2023',
    homeCount: 461,
    priceRange: '$400,000 - $1,000,000+',
    category: 'premium',
  },
  {
    slug: 'heritage-cadence',
    name: 'Heritage at Cadence',
    location: 'Henderson, NV (Cadence Master Plan)',
    city: 'Henderson',
    description: 'Newer Lennar community with resort-style amenities in Cadence',
    longDescription: 'Heritage at Cadence is a newer 55+ community by Lennar Homes featuring 450+ homes in the Cadence master plan. This resort-style community offers a modern community center, indoor lap pool, outdoor pool, billiards, crafts rooms, ballroom, bocce, tennis, horseshoe pits, and smart-home features.',
    amenities: [
      'Modern community center',
      'Indoor lap pool',
      'Outdoor resort-style pool',
      'Billiards room',
      'Crafts rooms',
      'Ballroom',
      'Bocce courts',
      'Tennis courts',
      'Horseshoe pits',
      'Smart-home features',
    ],
    floorplans: ['Single-story homes', 'Modern designs', 'Smart-home technology', 'Homes from 1,400 to 2,600 sq ft'],
    homesForSale: 4,
    featured: false,
    yearBuilt: '2020',
    homeCount: 450,
    priceRange: '$500,000 - $800,000',
    category: 'mid-size',
  },
  {
    slug: 'heritage-stonebridge',
    name: 'Heritage at Stonebridge',
    location: 'Summerlin, Las Vegas, NV (Stonebridge Master Plan)',
    city: 'Las Vegas',
    description: 'Newest Lennar community in Summerlin with smart-home features',
    longDescription: 'Heritage at Stonebridge is the newest 55+ community by Lennar Homes in Summerlin\'s Stonebridge master plan, featuring 421 homes built from 2021+. This modern community offers an 8,000 square foot clubhouse, fitness center, pool, athletic courts, walking trails, and smart-home features throughout.',
    amenities: [
      '8,000 sq ft clubhouse',
      'Fitness center',
      'Resort-style pool',
      'Athletic courts',
      'Walking trails',
      'Smart-home features',
      'Modern architecture',
    ],
    floorplans: ['Single-story homes', 'Smart-home technology', 'Modern designs', 'Homes from mid-400s to $800,000'],
    homesForSale: 7,
    featured: false,
    yearBuilt: '2021',
    homeCount: 421,
    priceRange: '$400,000 - $800,000',
    category: 'mid-size',
  },
  {
    slug: 'regency-summerlin',
    name: 'Regency at Summerlin',
    location: 'Summerlin, Las Vegas, NV',
    city: 'Las Vegas',
    description: 'Luxury Toll Brothers community with 22,000 sq ft clubhouse in Summerlin',
    longDescription: 'Regency at Summerlin by Toll Brothers offers 448 luxury homes with a spectacular 22,000 square foot clubhouse featuring indoor lap pool, outdoor resort-style pool, state-of-the-art fitness center, game rooms, and premium amenities throughout this prestigious Summerlin location.',
    amenities: [
      '22,000 sq ft clubhouse',
      'Indoor lap pool',
      'Outdoor resort-style pool',
      'Fitness center',
      'Game rooms',
      'Sports courts',
      'Walking trails',
      'Premium finishes',
    ],
    floorplans: ['Luxury single-story homes', 'Premium designs', 'Homes from 1,500 to 3,000+ sq ft'],
    homesForSale: 6,
    featured: false,
    yearBuilt: '2020',
    homeCount: 448,
    priceRange: '$600,000 - $1,200,000+',
    category: 'premium',
  },
  {
    slug: 'trilogy-sunstone',
    name: 'Trilogy Summerlin Sunstone',
    location: 'Summerlin, Las Vegas, NV (South Square)',
    city: 'Las Vegas',
    description: 'Premium 55+ community by Shea Homes with modern architecture',
    longDescription: 'Trilogy Sunstone in Summerlin\'s South Square offers 354 premium 55+ homes with Shea Homes\' Freedom Collection. This community features modern architecture, resort-style amenities, clubhouse, fitness center, art studio, outdoor pool, bocce ball courts, and thoughtfully designed homes for active adults seeking contemporary retirement living.',
    amenities: [
      'Modern clubhouse',
      'Fitness center',
      'Art studio',
      'Outdoor resort-style pool',
      'Bocce ball courts',
      'Sports courts',
      'Walking trails',
      'Modern architecture',
    ],
    floorplans: ['Freedom Collection homes', 'Modern designs', 'Single-story options', 'Homes from low $300,000s to mid $500,000s'],
    homesForSale: 5,
    featured: false,
    yearBuilt: '2022',
    homeCount: 354,
    priceRange: '$300,000 - $500,000',
    category: 'mid-size',
  },
  {
    slug: 'terra-bella',
    name: 'Terra Bella',
    location: 'Henderson, NV (Anthem Master Plan)',
    city: 'Henderson',
    description: 'Elevator-accessible condos by Lennar with 24,000 sq ft clubhouse',
    longDescription: 'Terra Bella in Henderson\'s Anthem master plan features approximately 400+ homes with nearly sold out status. This community by Lennar offers elevator-accessible condos, a 24,000 square foot clubhouse, fitness center, game room, pools, spa, and modern amenities, built from 2020+.',
    amenities: [
      '24,000 sq ft clubhouse',
      'Fitness center',
      'Game room',
      'Swimming pools',
      'Spa facilities',
      'Elevator-accessible condos',
      'Modern amenities',
    ],
    floorplans: ['Elevator-accessible condos', 'Modern designs', 'Lennar floor plans', 'Homes from $400,000 to $700,000'],
    homesForSale: 2,
    featured: false,
    yearBuilt: '2020',
    homeCount: 400,
    priceRange: '$400,000 - $700,000',
    category: 'mid-size',
  },
  // ESTABLISHED/SMALLER COMMUNITIES
  {
    slug: 'del-webb-north-ranch',
    name: 'Del Webb North Ranch',
    location: 'North Las Vegas, NV',
    city: 'North Las Vegas',
    description: 'Newest gated 55+ community in North Las Vegas',
    longDescription: 'Del Webb North Ranch is one of the newest 55+ communities in the Las Vegas area, offering gated security, resort-style pool, fitness center, sports courts, and modern home designs. This community represents the latest in active adult living with contemporary amenities and energy-efficient homes.',
    amenities: [
      'Gated community',
      'Resort-style pool',
      'Fitness center',
      'Sports courts',
      'Walking trails',
      'Modern architecture',
    ],
    floorplans: ['Single-story homes', 'Modern designs', 'Energy-efficient', 'Homes from 1,300 to 2,500 sq ft'],
    homesForSale: 6,
    featured: false,
    yearBuilt: '2024',
    homeCount: 300,
    priceRange: '$400,000 - $600,000',
    category: 'mid-size',
  },
  {
    slug: 'solera-stallion-mountain',
    name: 'Solera at Stallion Mountain',
    location: 'Henderson/Las Vegas, NV',
    city: 'Henderson',
    description: 'Mid-size 55+ community with resort-style facilities',
    longDescription: 'Solera at Stallion Mountain offers mid-size 55+ living with resort-style facilities, modern community center, and thoughtfully designed homes for active adults seeking quality amenities at a comfortable scale.',
    amenities: [
      'Modern community center',
      'Resort-style facilities',
      'Fitness center',
      'Swimming pools',
      'Sports courts',
      'Social activities',
    ],
    floorplans: ['Single-story homes', 'Modern designs', 'Various floor plans'],
    homesForSale: 4,
    featured: false,
    yearBuilt: '2010',
    homeCount: 500,
    priceRange: '$350,000 - $650,000',
    category: 'mid-size',
  },
  {
    slug: 'club-madeira-canyon',
    name: 'The Club at Madeira Canyon',
    location: 'Henderson, NV',
    city: 'Henderson',
    description: 'Luxury guard-gated community at elevation with mountain views',
    longDescription: 'The Club at Madeira Canyon is a luxury guard-gated 55+ community offering elevation with stunning mountain views, premium amenities, and exclusive lifestyle for discerning active adults seeking the finest in Las Vegas area retirement living.',
    amenities: [
      'Guard-gated security',
      'Elevation with views',
      'Mountain views',
      'Luxury amenities',
      'Premium facilities',
      'Exclusive lifestyle',
    ],
    floorplans: ['Luxury homes', 'Premium designs', 'Homes $800,000+'],
    homesForSale: 2,
    featured: false,
    yearBuilt: '2005',
    homeCount: 200,
    priceRange: '$800,000+',
    category: 'premium',
  },
  {
    slug: 'heritage-black-mountain-ranch',
    name: 'Heritage at Black Mountain Ranch',
    location: 'Henderson, NV (Black Mountain Ranch)',
    city: 'Henderson',
    description: '55+ community in Black Mountain Ranch Master Plan',
    longDescription: 'Heritage at Black Mountain Ranch offers 55+ living within the Black Mountain Ranch master plan, featuring recreation facilities, fitness center, and access to master plan amenities in this desirable Henderson location.',
    amenities: [
      'Recreation facilities',
      'Fitness center',
      'Swimming pools',
      'Access to master plan amenities',
      'Social activities',
    ],
    floorplans: ['Single-story homes', 'Various floor plans'],
    homesForSale: 3,
    featured: false,
    yearBuilt: '2008',
    homeCount: 350,
    priceRange: '$450,000 - $750,000',
    category: 'mid-size',
  },
  {
    slug: 'desert-shores',
    name: 'Desert Shores',
    location: 'Las Vegas, NV',
    city: 'Las Vegas',
    description: 'Waterfront community with lake views and golf courses',
    longDescription: 'Desert Shores offers a unique waterfront lifestyle in Las Vegas with stunning lake views, private beaches, and resort-style amenities. This established community features a mix of architectural styles and provides residents with an active, social lifestyle with golf, water activities, and community events.',
    amenities: [
      'Lakefront properties with beach access',
      'Private beaches and water activities',
      'Golf courses',
      'Swimming pools and spas',
      'Tennis courts',
      'Community centers',
      'Walking trails',
      'Waterfront dining options',
    ],
    floorplans: ['Single-story and two-story options', 'Lakefront and non-lakefront homes', 'Homes from 1,200 to 4,000+ sq ft'],
    homesForSale: 8,
    featured: false,
    yearBuilt: '1987',
    homeCount: 3000,
    priceRange: '$300,000 - $1,200,000',
    category: 'large',
  },
  // VALUE/BUDGET-FRIENDLY COMMUNITIES
  {
    slug: 'los-prados',
    name: 'Los Prados',
    location: 'Las Vegas, NV',
    city: 'Las Vegas',
    description: 'Best value 55+ community in Las Vegas area',
    longDescription: 'Los Prados offers an affordable active lifestyle with quality amenities at exceptional value. This smaller community provides active lifestyle amenities and affordable pricing, making it an excellent option for those seeking 55+ living on a budget.',
    amenities: [
      'Active lifestyle amenities',
      'Community pool',
      'Recreation facilities',
      'Social activities',
      'Affordable pricing',
    ],
    floorplans: ['Affordable homes', 'Various options', 'Homes from $300,000 to $500,000'],
    homesForSale: 8,
    featured: false,
    yearBuilt: '1990',
    homeCount: 600,
    priceRange: '$300,000 - $500,000',
    category: 'value',
  },
  {
    slug: 'tropicana-palms',
    name: 'Tropicana Palms',
    location: 'Las Vegas, NV (East Tropicana)',
    city: 'Las Vegas',
    description: 'Gated 55+ community near Clark County Preserve',
    longDescription: 'Tropicana Palms is a gated 55+ community on East Tropicana, close to Clark County Preserve & Nature Center. This community offers two pools, two spas, sauna, fitness center, pickleball, tennis, shuffleboard, and an active lifestyle at an affordable price point.',
    amenities: [
      'Two pools',
      'Two spas',
      'Sauna',
      'Fitness center',
      'Pickleball courts',
      'Tennis courts',
      'Shuffleboard',
      'Near nature preserve',
    ],
    floorplans: ['Affordable homes', 'Various floor plans'],
    homesForSale: 6,
    featured: false,
    yearBuilt: '1985',
    homeCount: 500,
    priceRange: '$250,000 - $450,000',
    category: 'value',
  },
  {
    slug: 'mera-henderson',
    name: 'Mera Henderson',
    location: 'Henderson, NV',
    city: 'Henderson',
    description: 'Newer 55+ community with modern resort-style facilities',
    longDescription: 'Mera Henderson is a newer 55+ community offering modern resort-style facilities and contemporary home designs. This new construction option provides active adults with quality amenities and modern living at an accessible price point.',
    amenities: [
      'Modern resort-style facilities',
      'Community center',
      'Fitness center',
      'Swimming pools',
      'Sports courts',
      'New construction',
    ],
    floorplans: ['New construction homes', 'Modern designs', 'Starting from low $300,000s'],
    homesForSale: 4,
    featured: false,
    yearBuilt: '2023',
    homeCount: 250,
    priceRange: '$300,000+',
    category: 'value',
  },
  // CONTINUING CARE COMMUNITIES
  {
    slug: 'las-ventanas',
    name: 'Las Ventanas',
    location: 'West Las Vegas, NV',
    city: 'Las Vegas',
    description: 'Award-winning continuing care retirement community',
    longDescription: 'Las Ventanas is an award-winning continuing care retirement community (CCRC) recognized by U.S. News 2024 for best continuing care and memory care. This full-service community offers concierge services, transportation, dining, full-service salon, fitness, pools, billiards, arts studio, and comprehensive care options.',
    amenities: [
      'Concierge services',
      'Transportation',
      'Dining services',
      'Full-service salon',
      'Fitness center',
      'Swimming pools',
      'Billiards',
      'Arts studio',
      'Continuing care options',
    ],
    floorplans: ['Apartments', 'Various sizes', 'Starting from $4,653/month'],
    homesForSale: 0,
    featured: false,
    yearBuilt: '2000',
    priceRange: 'Entrance fees from $181,440, monthly from $4,653',
    category: 'continuing-care',
  },
  {
    slug: 'carnegie-heights',
    name: 'Carnegie Heights',
    location: 'Henderson, NV',
    city: 'Henderson',
    description: 'Age-restricted independent living near Henderson Hospital',
    longDescription: 'Carnegie Heights offers age-restricted independent living with no long-term leases or buy-ins required. This community features recreation center, pickleball, tennis, pools, golf club nearby, walking trails, and proximity to lake recreation including paddleboarding, kayaking, and pedal boats. Near new Henderson Hospital.',
    amenities: [
      'Recreation center',
      'Pickleball courts',
      'Tennis courts',
      'Swimming pools',
      'Golf nearby',
      'Walking trails',
      'Lake recreation access',
      'Near Henderson Hospital',
    ],
    floorplans: ['Independent living homes', 'No buy-ins required', 'Homes from $432,000 to $819,000'],
    homesForSale: 5,
    featured: false,
    yearBuilt: '2006',
    homeCount: 300,
    priceRange: '$432,000 - $819,000',
    category: 'continuing-care',
  },
]
